

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


jobs:
  - job: Debug
    steps:
      - script: echo hello from the Debug Build. 
  - job: Release
    dependsOn: Debug
    steps:
      - script: echo hello from the Release Build. 
      

