

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


jobs:
  - job: ToBeFailed
    steps:
      - script: exit 1
  
  - job: DependendOnFailure
    dependsOn: ToBeFailed
    condition: failed()
    steps:
      - script: echo This runs when first Job fails. 

  - job: DependingAll
    dependsOn: 
      - ToBeFailed
      - DependendOnFailure
    condition: succeeded('DependendOnFailure')
    steps:
      - script: echo This will run when the second Job succeeds. 
    
      

