

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: A
  jobs:
  - job: A1
    steps:
      - bash: echo A1
  - job: A2

- stage: B
  jobs:
  - job: B1
  - job: B2
    steps:
      - bash: echo B2